name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_TO_VPS }}" > ~/.ssh/key
        chmod 600 ~/.ssh/key
        ssh-keyscan -H 145.223.94.102 >> ~/.ssh/known_hosts

    - name: Build & Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy application via SSH
      run: |
        ssh -i ~/.ssh/key root@145.223.94.102 << 'EOF'
          set -e
          cd /var/www/crudapp/
          rm -rf publish/*
        EOF

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.8
      with:
        host: 145.223.94.102
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY_TO_VPS }}
        source: "publish/*"
        target: "/var/www/crudapp/publish"

    - name: Restart app service
      run: |
        ssh -i ~/.ssh/key root@145.223.94.102 << 'EOF'
          systemctl restart crudapp
        EOF
