name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_TO_VPS }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 145.223.94.102 >> ~/.ssh/known_hosts

    - name: Build & Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy via rsync
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" publish/ root@145.223.94.102:/var/www/crudapp/publish/

    - name: Set permissions and restart service
      run: |
        ssh -i ~/.ssh/id_rsa root@145.223.94.102 << 'EOF'
          set -e
          chown -R www-data:www-data /var/www/crudapp/publish
          systemctl restart crudapp
        EOF
